### ISSUE TITLE
Inaccessible reference

### ISSUE THREAD

**Issue by johnwebner** [jecki/DHParser#1]
I would like to read the reference: 
Dominikus Herzberg: Eine einfache Grammatik für LaTeX, Blog-Post, September, 18th 2008 on denkspuren. gedanken, ideen, anregungen und links rund um informatik-themen
Unfortunately the blog is open to invited readers only.
Do you have any copy?

**Comment by jecki** [comment]
Unfortunately, I did not make a copy, but I just mailed the author of the blog about its not being accesible any more. I'll let you know about any answer, I receive.
